language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t aquintero446/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true aquintero446/react-test npm run test

after_success:
    - docker build -t aquintero446/multi-client ./client
    - docker build -t aquintero446/multi-nginx ./nginx
    - docker build -t aquintero446/multi-server ./server
    - docker build -t aquintero446/multi-worker ./worker
    # Log in to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Push images to docker hub
    - docker push aquintero446/multi-client
    - docker push aquintero446/multi-nginx
    - docker push aquintero446/multi-server
    - docker push aquintero446/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker-andres"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-774154012305"
    bucket_path: "multi-docker-andres"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
      